#
thisProjectName=spring-boot-batch
deployFileName=spring-boot-batch.jar

#
localRepository=D:/zRepositoryForMaven


#
projectGroup=com.example
projectVersion=0.0.1

javaEncoding=UTF-8
javaVersion=17


# spring-boot version
springBootVersion=3.5.5
springCloudVersion=2025.0.0
springDependencyManagementVersion=1.1.7

# 3rd party library version
hidetakeSshVersion=2.12.0
jasyptSpringBootVersion=3.0.5
jettyReactiveHttpclientVersion=3.0.6
jettyClientVersion=11.0.12
junitJupiterVersion=5.7.1
lombokVersion=1.18.22
mybatisSpringBootVersion=3.0.5

# gradle options
org.gradle.warning.mode=all
