########## local, dev, prd 공통 설정 ##########

project:
  name: sb2-web
  version: 1.0
  base-pkg: com.example #// FIXME CHECK-package 확인 (공통 설정)
  base-pkg-2: com.sample #// FIXME CHECK-package 확인 (공통 설정)
  locale: ko_KR
  time-zone: Asia/Seoul
#  locale: en_US
#  time-zone: UTC


spring:
  application:
    name: ${project.name}
  profiles:
    active:
      - local
